In [1]:
from PIL import Image
import os, os.path
import numpy as np
import cv2
import pandas as pd

dir = "C:/Users/Rashika/Desktop/DMDD Project/TestImages"
#dir = "C:/Users/Rashika/Desktop/DMDD Project/Images"
r = []
n=0
valid_images = [".jpg",".jpeg",".png"]
for root, dirs, files in os.walk(dir):
    df= pd.DataFrame(columns = ['Name','Shape', 'Size',
                             'Datatype','Category','SubCategory','ObjectName','X','Y','Z','Shadow'])
    for name in files:
        ext = os.path.splitext(name)
        if ext[1].lower() not in valid_images:
            continue
        else:
            namesplit = ext[0].split('_')
            img = cv2.imread(os.path.join(root,name))##entire path of image
           ## print(os.path.join(root,name))
            i4=name
            i1=img.shape
            i2=os.path.getsize(os.path.join(root,name))
            i3=img.dtype
            i5 = namesplit[0]
            i6 = namesplit[1]
            i7 = namesplit[2]
            i8 = namesplit[3]
            i9 = namesplit[4]
            i10 = namesplit[5]
            i11 = namesplit[6]
            #print("name",i4)
            #print('Image shape is \n',img.shape) 
            #print('Image size is \n', os.path.getsize(os.path.join(root,name)))
            #print ('Image datatype is \n',img.dtype)
            df.loc[n, 'Shape'] = i1
            df.loc[n, 'Size'] = i2
            df.loc[n, 'Datatype'] = i3
            df.loc[n,'Name']=i4
            df.loc[n,'Category']=i5
            df.loc[n,'SubCategory']=i6
            df.loc[n,'ObjectName']=i7
            df.loc[n,'X']=i8[1:]
            df.loc[n,'Y']=i9[1:]
            df.loc[n,'Z']=i10[1:]
            df.loc[n,'Shadow']=i11
            n+=1

In [2]:
df
df.to_csv("SampleTestImages.csv")

,Name,Shape,Size,Datatype,Category,SubCategory,ObjectName,X,Y,Z,Shadow
0,category1_subcat1_objectname1_X0_Y0_Z0_Yes.jpg,"(194, 259, 3)",5616,uint8,category1,subcat1,objectname1,0,0,0,Yes
1,category2_subcat2_objectname2_X45_Y45_Z45_No.jpg,"(182, 276, 3)",6791,uint8,category2,subcat2,objectname2,45,45,45,No